title: 'HowAgile'
description: 'How Agile 好敏捷 | 敏捷思維的推手 | 協助你邁向敏捷之道'
themeConfig:
    search: false
    nav:
        -   text: 'Home'
            link: '/'
        -   text: '培訓師'
            link: '/#培訓師'
        -   text: '課程'
            link: '/#課程'
base: /howagile.github.io/